# Generated by Django 4.0.5 on 2022-06-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theawwards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('caption', models.CharField(max_length=10000, verbose_name='Caption')),
            ],
        ),
    ]
