# Generated by Django 4.0.5 on 2022-06-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theawwards', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='overall_score',
            new_name='votes',
        ),
    ]
